name: Release
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v3

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: extractions/setup-just@v1

    - uses: DeLaGuardo/setup-clojure@10.2
      with:
        cli: latest

    - name: Build
      run: |
        just build

    - name: Release
      if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: |
        just release
